export enum AnalyticsEvent {
  ERROR_OCCURRED = 'error_occurred',
  GUI_SCREEN_VIEW = 'gui_screen_view',
  GUI_HELP_CHAT_OPENED = 'gui_help_chat_opened',
  AUTH_LOGIN_STARTED = 'auth_login_started',
  AUTH_LOGIN_SUCCESS = 'auth_login_success',
  AUTH_LOGIN_FAILED = 'auth_login_failed',
  AUTH_LOGOUT = 'auth_logout',
  AUTH_SIGNUP_STARTED = 'auth_signup_started',
  AUTH_SIGNUP_SUCCESS = 'auth_signup_success',
  AUTH_SIGNUP_FAILED = 'auth_signup_failed',
  AUTH_ROLE_SWITCH_STARTED = 'auth_role_switch_started',
  AUTH_ROLE_SWITCH_SUCCESS = 'auth_role_switch_success',
  AUTH_ROLE_SWITCH_FAILED = 'auth_role_switch_failed',
  AUTH_ACCOUNT_DELETED = 'auth_account_deleted',
  DRIVER_ONBOARDING_STARTED = 'driver_onboarding_started',
  DRIVER_ONBOARDING_STEP_1_COMPLETED = 'driver_onboarding_step_1_completed',
  DRIVER_ONBOARDING_STEP_2_COMPLETED = 'driver_onboarding_step_2_completed',
  DRIVER_ONBOARDING_STEP_3_COMPLETED = 'driver_onboarding_step_3_completed',
  DRIVER_ONBOARDING_COMPLETED = 'driver_onboarding_completed',
  DRIVER_ONLINE = 'driver_online',
  DRIVER_OFFLINE = 'driver_offline',
  DRIVER_LOCATION_UPDATE = 'driver_location_update',
  PASSENGER_DRIVER_VIEWED = 'passenger_driver_viewed',
  PASSENGER_DRIVER_CALLED = 'passenger_driver_called',
  PASSENGER_DRIVER_WHATSAPP = 'passenger_driver_whatsapp',
  PASSENGER_DRIVER_FILTER_CHANGED = 'passenger_driver_filter_changed',
  CHAT_MESSAGE_SENT = 'chat_message_sent',
  CHAT_MESSAGE_RECEIVED = 'chat_message_received',
  CHAT_CONVERSATION_OPENED = 'chat_conversation_opened',
  CHAT_CONVERSATION_CREATED = 'chat_conversation_created',
  CHAT_MESSAGES_READ = 'chat_messages_read',
  NOTIFICATION_RECEIVED = 'notification_received',
  NOTIFICATION_PERMISSION_REQUESTED = 'notification_permission_requested',
  NOTIFICATION_PERMISSION_GRANTED = 'notification_permission_granted',
  NOTIFICATION_PERMISSION_DENIED = 'notification_permission_denied',
  FCM_TOKEN_UPDATED = 'fcm_token_updated',
  FCM_TOKEN_CLEARED = 'fcm_token_cleared',
}

export type AnalyticsEventType = AnalyticsEvent;

